name: chat_manager
description: A demo project to simulate server-local chat synchronization, using chain mechanism. The project architecture is based on BLoC and Repository layer pattern.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-334.3.beta

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  stream_channel: ^2.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
